[package]
name = "rust-web-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.22.0", features = ["full"] }
axum = "0.5.17"
yaml-rust = "0.4"
async-graphql = "5.0.1"