[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
serde_yaml = "0.9.21"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.22.0", features = ["full"] }
axum = "0.5.17"
async-graphql = "5.0.1"
lazy_static = "1.4.0"
mysql = "18.1.0"
diesel = { version = "2.1.0", features = ["mysql"] }
dotenvy = "0.15.7"