############################# config file #############################
profiles:
  active: dev
############################# application #############################
application:
  name: rust-web-application
  port: 8080
############################# redis #############################
redis:
  endpoint: redis://127.0.0.1/
  port: 6379
  username:
  password:
############################# database #############################
database:
  url : mysql://root:123456@localhost/rwf?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
  max_size: 5

############################# jwt #############################
jwt:
  token-expire-time: 3600 # seconds