############################# config file #############################
profiles:
  active: dev
############################# application #############################
application:
  name: rust-web-application
  port: 8080
############################# redis #############################



############################# database #############################