############################# config file #############################
profiles:
  active: dev
############################# application #############################
application:
  name: rust-web-application
  port: 8080
############################# redis #############################



############################# database #############################
database:
  url : mysql://root:123456@localhost/rwf?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  username: root
  password: 123456